 
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=slhf
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  mysql_ui:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_DATABASE=slhf
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=password
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
